In [2]:
import pandas as pd

file_path = "/workspaces/gcgf-vibe-hackathon/data/경기도_시군구별_읍면동_위치정보.csv"

df = pd.read_csv(file_path, encoding="cp949")

# 데이터 확인
df.head()

,admdong_cd,admdong_nm,signgu_cd,signgu_nm,shape
0,1111067000,창신1동,11110,종로구,MULTIPOLYGON (((127.01265029501917 37.57537987...
1,1111068000,창신2동,11110,종로구,MULTIPOLYGON (((127.00884193394717 37.58045184...
2,1111069000,창신3동,11110,종로구,MULTIPOLYGON (((127.01473834680976 37.58220580...
3,1111070000,숭인1동,11110,종로구,MULTIPOLYGON (((127.01495128647338 37.58212929...
4,1111071000,숭인2동,11110,종로구,MULTIPOLYGON (((127.01875247123537 37.57752617...

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3496 entries, 0 to 3495
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   admdong_cd  3496 non-null   int64
 1   admdong_nm  3496 non-null   object
 2   signgu_cd   3496 non-null   int64
 3   signgu_nm   3496 non-null   object
 4   shape       3496 non-null   object
dtypes: int64(2), object(3)
memory usage: 136.7+ KB

In [4]:
gyonggi_df = df[(df["signgu_cd"] >= 41000) & (df["signgu_cd"] < 42000)]

In [5]:
gyonggi_df

,admdong_cd,admdong_nm,signgu_cd,signgu_nm,shape
162,4111752000,매탄2동,41117,수원시 영통구,MULTIPOLYGON (((127.04798708361295 37.27352054...
459,4113556000,정자2동,41135,성남시 분당구,MULTIPOLYGON (((127.11659900616353 37.37163577...
767,4113554500,정자동,41135,성남시 분당구,MULTIPOLYGON (((127.11659900616353 37.37163577...
771,4113357000,상대원1동,41133,성남시 중원구,MULTIPOLYGON (((127.17854114409465 37.45446930...
773,4127354500,원곡동,41273,안산시 단원구,MULTIPOLYGON (((126.79084252566851 37.33920473...
...,...,...,...,...,...
3407,4136034000,수동면,41360,남양주시,MULTIPOLYGON (((127.26652444529324 37.78044909...
3447,4159061000,동탄7동,41590,화성시,MULTIPOLYGON (((127.09868498914176 37.17748859...
3449,4111759300,망포1동,41117,수원시 영통구,MULTIPOLYGON (((127.05154058453941 37.23435483...
3490,4128164000,행신1동,41281,고양시 덕양구,MULTIPOLYGON (((126.83427422942329 37.62427403...
3492,4155034000,미양면,41550,안성시,MULTIPOLYGON (((127.20065286993479 36.98466219...

In [6]:
save_path = "/workspaces/gcgf-vibe-hackathon/data/gyonggi_dong_geo_df.csv"

gyonggi_df.to_csv(save_path, index=False, encoding="utf-8-sig")